package proyecto;

import javax.swing.ImageIcon;


public class FrmInicial extends javax.swing.JFrame {

    /**
     * Creates new form inicial
     */
    
    public FrmInicial() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar pantalla 
        Imagen im = new Imagen(jPanel1);
        jPanel1.add(im).repaint();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        this.setDefaultCloseOperation(FrmInicial.DO_NOTHING_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmTemas = new javax.swing.JMenu();
        jmiBinario = new javax.swing.JMenuItem();
        jmiOctal = new javax.swing.JMenuItem();
        jmiHexadecimal = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jmiSobreNosotros = new javax.swing.JMenuItem();
        jmiManual = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setName("frmInicial"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jmTemas.setText("Temas");

        jmiBinario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiBinario.setText("Binario");
        jmiBinario.setName("frmInicial"); // NOI18N
        jmiBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBinarioActionPerformed(evt);
            }
        });
        jmTemas.add(jmiBinario);

        jmiOctal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiOctal.setText("Octal");
        jmiOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOctalActionPerformed(evt);
            }
        });
        jmTemas.add(jmiOctal);

        jmiHexadecimal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiHexadecimal.setText("Hexadecimal");
        jmiHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHexadecimalActionPerformed(evt);
            }
        });
        jmTemas.add(jmiHexadecimal);

        jmiSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmTemas.add(jmiSalir);

        jMenuBar1.add(jmTemas);

        jmAyuda.setText("Ayuda");
        jmAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAyudaActionPerformed(evt);
            }
        });

        jmiSobreNosotros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmiSobreNosotros.setText("Sobre Nosotros");
        jmiSobreNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreNosotrosActionPerformed(evt);
            }
        });
        jmAyuda.add(jmiSobreNosotros);

        jmiManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmiManual.setText("Manual de Uso");
        jmiManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManualActionPerformed(evt);
            }
        });
        jmAyuda.add(jmiManual);

        jMenuBar1.add(jmAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBinarioActionPerformed
        FrmBinario frmBinario = new FrmBinario();
        frmBinario.setVisible(true);
    }//GEN-LAST:event_jmiBinarioActionPerformed

    private void jmiOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOctalActionPerformed
        FrmOctal frmOctal = new FrmOctal();
        frmOctal.setVisible(true);
    }//GEN-LAST:event_jmiOctalActionPerformed

    private void jmiHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHexadecimalActionPerformed
        FrmHexadecimal frmHexa = new FrmHexadecimal();
        frmHexa.setVisible(true);
    }//GEN-LAST:event_jmiHexadecimalActionPerformed

    private void jmAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAyudaActionPerformed
  
    }//GEN-LAST:event_jmAyudaActionPerformed

    private void jmiSobreNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreNosotrosActionPerformed
        FrmAcercaDe frmAcercaDe = new FrmAcercaDe();
        frmAcercaDe.setVisible(true);
    }//GEN-LAST:event_jmiSobreNosotrosActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManualActionPerformed
        Procesos manual = new Procesos();
        manual.cargarArchivo();
    }//GEN-LAST:event_jmiManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenu jmTemas;
    private javax.swing.JMenuItem jmiBinario;
    private javax.swing.JMenuItem jmiHexadecimal;
    private javax.swing.JMenuItem jmiManual;
    private javax.swing.JMenuItem jmiOctal;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiSobreNosotros;
    // End of variables declaration//GEN-END:variables
}
